#!/bin/sh

# PROVIDE: StakeCoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# StakeCoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable StakeCoin service.
# StakeCoin_config (path): Set to /usr/local/etc/StakeCoin.conf by default.
# StakeCoin_user:  The user account StakeCoin daemon runs as. It uses 'root' user by default.
# StakeCoin_group: The group account StakeCoin daemon runs as. It uses 'wheel' group by default.
# StakeCoin_datadir (str): Default to "/var/db/StakeCoin". Base data directory.

. /etc/rc.subr

name=StakeCoin
rcvar=StakeCoin_enable

: ${StakeCoin_enable:=NO}
: ${StakeCoin_config=/usr/local/etc/StakeCoin.conf}
: ${StakeCoin_datadir=/var/db/StakeCoin}
: ${StakeCoin_user="root"}
: ${StakeCoin_group="wheel"}

required_files=${StakeCoin_config}
command=/usr/local/bin/StakeCoind
StakeCoin_chdir=${StakeCoin_datadir}
pidfile="${StakeCoin_datadir}/StakeCoind.pid"
stop_cmd=StakeCoin_stop
command_args="-conf=${StakeCoin_config} -datadir=${StakeCoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

StakeCoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${StakeCoin_datadir}
	[ $? -eq 0 ] && chown -R ${StakeCoin_user}:${StakeCoin_group} ${StakeCoin_datadir}
}

StakeCoin_prestart()
{
	if [ ! -d "${StakeCoin_datadir}/." ]; then
		StakeCoin_create_datadir || return 1
	fi
}

StakeCoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

StakeCoin_stop()
{
    StakeCoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${StakeCoin_config} -datadir=${StakeCoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
